### ISSUE TITLE
Command completion callback

### ISSUE THREAD

**Issue by Cross22** [WowWeeLabs/MiP-BLE-Protocol#11]
Is there any way to find out if a previously sent command has been completed? For example when playing a sound, the clips can be anywhere between 0.5 and 5 seconds. When is it safe to play another one? Same for the drive commands..

**Comment by hongkongkiwi** [comment]
For the sounds commands they can be queued in the protocol. For the drive commands just 1 or 2 or queued. Feel free to continuously repeat them without harm.

**Comment by hongkongkiwi** [comment]
To clarify we did not build in a callback command as we didn't need it and wanted to save BLE bandwidth.
