### ISSUE TITLE
Get radar response command

### ISSUE THREAD

**Issue by tramuntanal** [WowWeeLabs/MiP-BLE-Protocol#15]
In the protocol there is a Radar Response but there is no documented command to invoke it.
The doc states that "Radar Response" stands for cmd 0x0C, but this command effectively corresponds to "Set Gesture Or Radar Mode".

How can I know if the MiP has any obstacle in front?

**Comment by adamgreen** [comment]
Use "Set Gesture or Radar Mode" with a parameter of 0x04 to set MiP into Radar mode. The MiP will then send "Radar Response" notifications as the detected distance to objects change.

**Comment by tramuntanal** [comment]
Confirmed, I get it to work.
thanks!
