### ISSUE TITLE
BLE protocol for CHiP

### ISSUE THREAD

**Issue by blokhin** [WowWeeLabs/MiP-BLE-Protocol#17]
Hi and sorry for partial off-topic.

WowWee CHiP is a robot-dog, able to recognize voice commands and navigate on its own indoors.

WowWee said sometime ago, that the SDK or bluetooth specs for CHiP are planned. Are there any updates on that?

Thanks a lot.

**Comment by sailimc** [comment]
Hello blokhin,

The SDK is still in progress, sorry for the delay. ETA end of August.

Cheers
Forrest

**Comment by skaromny** [comment]
is the SDK already released somewhere? thanks

**Comment by aenikata** [comment]
I'd be keen to see when it's released, too - given replacement Smartbands are rarer than hen's teeth, there's a growing number of these adorable little machines looking for an ongoing use, and I'd be keen to see what you're able to do with it with the SDK

**Comment by adamgreen** [comment]
CHiP SDKs for iOS and Android appear to now be released:
* [CHIP-iOS-SDK](https://github.com/WowWeeLabs/CHIP-iOS-SDK)
* [CHIP-Android-SDK](https://github.com/WowWeeLabs/CHIP-Android-SDK)

**Comment by blokhin** [comment]
Follow-up concerning remote BLE control: https://github.com/WowWeeLabs/CHIP-iOS-SDK/issues/2#issuecomment-362910392
